name = "GridCode3D"
version = "1.1.1"
license = "MIT"
author = "Lewis McMillan"
maintainer = "lewisfish92"
copyright = "2023 Lewis McMillan"

[[executable]]
name = "mcgrid"
source-dir = "src"
main = "mcpolar.f90"