ran2 – gridMCRT
ran2 Function
3 statements
Source File
public function ran2()
Wrapper function to fortran internal random number generator Generates a random number in the range [0,1.)
Arguments
None
Return Value real
Called by
Contents
Source Code
ran2
Source Code
    real function ran2()
    !! Wrapper function to fortran internal random number generator
    !! Generates a random number in the range [0,1.)
        call random_number(ran2)
    end function ran2
Call graph
isotropic_point_src calls ran2
ranu calls ran2
scatter calls ran2
tauint1 calls ran2
mcpolar calls ran2, isotropic_point_src, tauint1