tauint1 – gridMCRT
tauint1 Subroutine
44 statements
Source File
public subroutine tauint1(packet, grid)
Uses
iarray
random_mod
photon_class
gridset_mod
vector_class
optical depth integration subroutine. The main workhorse of MCRT
Arguments
Type Intent Optional Attributes Name
type(photon), intent(inout) :: packet
packet to move through the grid
type(cart_grid), intent(in) :: grid
grid that the packet moves through
Calls
Called by
Contents
Source Code
tauint1
Source Code
    subroutine tauint1(packet, grid)
    !! optical depth integration subroutine. The main workhorse of MCRT
        use gridset_mod,  only : cart_grid
        use iarray,       only : rhokap
        use photon_class, only : photon
        use random_mod,   only : ran2
        use vector_class, only : vector
        !> packet to move through the grid
        type(photon),    intent(inout) :: packet
        !> grid that the packet moves through
        type(cart_grid), intent(in)    :: grid
        ! intermediate position
        type(vector) :: pos
        real    :: tau, taurun, taucell, d, dcell
        integer :: celli, cellj, cellk
        logical :: dir(3)
        !change grid origin to lower left of the grid
        pos = packet%pos + grid%dim
        ! store current voxel in temp variables
        celli = packet%xcell
        cellj = packet%ycell
        cellk = packet%zcell
        ! setup to start integrating
        taurun = 0.
        d = 0.
        dir = (/.FALSE., .FALSE., .FALSE./)
        !sample optical distance
        tau = -log(ran2())
        do
            dir = (/.FALSE., .FALSE., .FALSE./)
            !get distance to nearest wall in direction dir
            dcell = wall_dist(packet, grid, celli, cellj, cellk, pos, dir)
            !calculate optical distnace to cell wall
            taucell = dcell * rhokap(celli,cellj,cellk)
            if(taurun + taucell < tau)then!still some tau to move
                taurun = taurun + taucell
                d = d + dcell
                call update_pos(packet, grid, pos, celli, cellj, cellk, dcell, .TRUE., dir)
            else!moved full distance
                dcell = (tau - taurun) / rhokap(celli,cellj,cellk)
                d = d + dcell
                call update_pos(packet, grid, pos, celli, cellj, cellk, dcell, .FALSE., dir)
                exit
            end if
            if(celli == -1 .or. cellj == -1 .or. cellk == -1)then
                packet%tflag = .true.
                exit
            end if
        end do
        ! move back to grid with origin at the centre
        packet%pos = pos - grid%dim
        packet%xcell = celli
        packet%ycell = cellj
        packet%zcell = cellk
    end subroutine tauint1
Call graph
tauint1 calls ran2, update_pos, wall_dist
update_pos calls update_voxels
mcpolar calls tauint1