update_pos – gridMCRT
update_pos Subroutine
60 statements
Source File
private subroutine update_pos(packet, grid, pos, celli, cellj, cellk, dcell, wall_flag, dir)
Uses
photon_class
random_mod
utils
vector_class
gridset_mod
routine that upates postions of photon and calls fresnel routines if photon leaves current voxel
Arguments
Type Intent Optional Attributes Name
type(photon), intent(in) :: packet
photon object
type(cart_grid), intent(in) :: grid
grid object
type(vector), intent(inout) :: pos
current photon position
integer, intent(inout) :: celli
current voxel ID
integer, intent(inout) :: cellj
current voxel ID
integer, intent(inout) :: cellk
current voxel ID
real(kind=wp), intent(in) :: dcell
distance phton will travel across a cell
logical, intent(in) :: wall_flag
flag is true if we hit a cell wall
logical, intent(in) :: dir(:)
logical array. 1 entry is always true. the true entry represents which cell wall we will hit
Calls
Called by
Contents
Source Code
update_pos
Source Code
    subroutine update_pos(packet, grid, pos, celli, cellj, cellk, dcell, wall_flag, dir)
    !! routine that upates postions of photon and calls fresnel routines if photon leaves current voxel
        use gridset_mod,  only : cart_grid
        use photon_class, only : photon
        use random_mod,   only : ran2
        use utils,        only : str
        use vector_class, only : vector
        !> photon object
        type(photon),    intent(in)    :: packet
        !> current photon position
        type(vector),    intent(inout) :: pos
        !> grid object
        type(cart_grid), intent(in)    :: grid
        !> distance phton will travel across a cell
        real(kind=wp),   intent(in)    :: dcell
        !> current voxel ID
        integer,         intent(inout) :: celli, cellj, cellk
        !> flag is true if we hit a cell wall
        logical,         intent(in)    :: wall_flag
        !> logical array. 1 entry is always true. the true entry represents which cell wall we will hit
        logical,         intent(in)    :: dir(:)
        ! if we hit a wall
        if(wall_flag)then
            ! in the x direction
            if(dir(1))then
                if(packet%dir%x > 0._wp)then
                    pos%x = grid%xface(celli+1) + grid%delta
                    celli = celli + 1
                elseif(packet%dir%x < 0._wp)then
                    pos%x = grid%xface(celli) - grid%delta
                    celli = celli - 1
                else
                    error stop 'Error in x dir in update_pos'
                end if
                pos%y = pos%y + packet%dir%y*dcell
                pos%z = pos%z + packet%dir%z*dcell
            ! y direction
            elseif(dir(2))then
                if(packet%dir%y > 0._wp)then
                    pos%y = grid%yface(cellj+1) + grid%delta
                    cellj = cellj + 1
                    elseif(packet%dir%y < 0._wp)then
                        pos%y = grid%yface(cellj) - grid%delta
                        cellj = cellj - 1
                    else
                        error stop 'Error in y dir in update_pos'
                    end if
                pos%x = pos%x + packet%dir%x*dcell
                pos%z = pos%z + packet%dir%z*dcell
            ! z direction
            elseif(dir(3))then
                if(packet%dir%z > 0._wp)then
                    pos%z = grid%zface(cellk+1) + grid%delta
                    cellk = cellk + 1
                elseif(packet%dir%z < 0._wp)then
                    pos%z = grid%zface(cellk) - grid%delta
                    cellk = cellk - 1
                else
                    error stop 'Error in z dir in update_pos'
                end if
                pos%x = pos%x + packet%dir%x*dcell
                pos%y = pos%y + packet%dir%y*dcell
            else
                error stop 'Error in update_pos...'
            end if
        else
            ! we dont hit a wall
            pos = pos + packet%dir * dcell
        end if
        if(wall_flag)then
            ! if we hit a wall, get current voxel
            call update_voxels(pos, grid, celli, cellj, cellk)
        end if
    end subroutine update_pos
Call graph
update_pos calls update_voxels
tauint1 calls update_pos
mcpolar calls tauint1