update_voxels – gridMCRT
update_voxels Subroutine
13 statements
Source File
private pure subroutine update_voxels(pos, grid, celli, cellj, cellk)
Uses
vector_class
gridset_mod
updates the current voxel based upon position
Arguments
Type Intent Optional Attributes Name
type(vector), intent(in) :: pos
current photon position vector
type(cart_grid), intent(in) :: grid
grid object
integer, intent(inout) :: celli
current voxel ID. To be updated
integer, intent(inout) :: cellj
current voxel ID. To be updated
integer, intent(inout) :: cellk
current voxel ID. To be updated
Called by
Contents
Source Code
update_voxels
Source Code
    pure subroutine update_voxels(pos, grid, celli, cellj, cellk)
    !! updates the current voxel based upon position
        use gridset_mod,  only : cart_grid
        use vector_class, only : vector
        !> current photon position vector
        type(vector),    intent(in)    :: pos
        !> grid object
        type(cart_grid), intent(in)    :: grid
        !> current voxel ID. To be updated
        integer,         intent(inout) :: celli, cellj, cellk
        celli = floor(grid%nxg * (pos%x) / (2._wp * grid%dim%x)) + 1
        cellj = floor(grid%nyg * (pos%y) / (2._wp * grid%dim%y)) + 1
        cellk = floor(grid%nzg * (pos%z) / (2._wp * grid%dim%z)) + 1
        if(celli > grid%nxg .or. celli < 1)celli = -1
        if(cellj > grid%nyg .or. cellj < 1)cellj = -1
        if(cellk > grid%nzg .or. cellk < 1)cellk = -1
    end subroutine update_voxels
Call graph
update_pos calls update_voxels
tauint1 calls update_pos
mcpolar calls tauint1