str – gridMCRT
str Interface
8 statements
Source File
public interface str
functions to turn numerical variables into strings
Calls
Called by
Contents
Module Procedures
str_I32 str_I64 str_Iarray str_R8 str_R8array str_logicalarray
Module Procedures
private function str_I32(i)
convert an int32 integer into a string
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: i
input int to convert into string
Return Value character(len=:), allocatable
private function str_I64(i)
convert an int64 integer into a string
Arguments
Type Intent Optional Attributes Name
integer(kind=Int64), intent(in) :: i
input int to convert into string
Return Value character(len=:), allocatable
private function str_iarray(i)
convert an int32 integer array into a string
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i(:)
input int array to convert into string
Return Value character(len=:), allocatable
private function str_R8(i)
convert an double precision float into a string
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: i
input float to convert into string
Return Value character(len=:), allocatable
private function str_R8array(a)
convert an double precision float array into a string
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: a(:)
input float array to convert into string
Return Value character(len=:), allocatable
private function str_logicalarray(a)
convert an logical array into a string
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: a(:)
input logical array to convert into string
Return Value character(len=:), allocatable
Call graph
str calls str_i32, str_i64, str_iarray, str_logicalarray, str_r8, str_r8array
mcpolar calls str