name: docs

on: [push, pull_request]
permissions:
    contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install ford
    - name: Build Documentation
      run: ford docs.md
    - uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: docs