name: docs

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      run:
        echo "::set-output name=result::${{ env.DEPLOY_BRANCH }}"
      env:
        DEPLOY_BRANCH: ${{ secrets.DEPLOY_BRANCH && contains(github.ref, secrets.DEPLOY_BRANCH) && 1 || 0 }}
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install ford
    - name: Build Documentation
      run: ford docs.md
    - uses: JamesIves/github-pages-deploy-action@4.1.6
      if: ${{&& steps.deploy.outputs.result != 0 }}
      with:
        branch: gh-pages
        folder: docs